import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { PointerLockControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/PointerLockControls.js';

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x9bb5b2); scene.fog=new THREE.Fog(0x9bb5b2,35,150);
const camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,300); camera.position.set(0,2,8);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; document.querySelector('#game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdcecff,0x34433d,2.1)); const sun=new THREE.DirectionalLight(0xfff0cf,3); sun.position.set(-30,50,20); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);
const controls=new PointerLockControls(camera,document.body); document.body.addEventListener('click',()=>controls.lock());
const keys={}; addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')interact();if(e.code==='KeyF')startCombat()}); addEventListener('keyup',e=>keys[e.code]=false);
function mat(c,rough=1){return new THREE.MeshStandardMaterial({color:c,roughness:rough})}
const ground=new THREE.Mesh(new THREE.PlaneGeometry(240,240),mat(0x46564a));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
function tree(x,z,s=1){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.28*s,.4*s,3*s,8),mat(0x5b4330));trunk.position.y=1.5*s;const crown=new THREE.Mesh(new THREE.DodecahedronGeometry(2.1*s,1),mat(0x243f36));crown.position.y=4.1*s;crown.castShadow=true;g.add(trunk,crown);g.position.set(x,0,z);scene.add(g)}
for(let i=0;i<65;i++){const a=Math.random()*Math.PI*2,r=15+Math.random()*80;tree(Math.cos(a)*r,Math.sin(a)*r,.55+Math.random()*1.3)}
function rock(x,z,s){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(s,1),mat(0x59605b));m.position.set(x,s*.45,z);m.scale.y=.65;m.castShadow=true;scene.add(m)} for(let i=0;i<30;i++){const a=Math.random()*6.28,r=10+Math.random()*85;rock(Math.cos(a)*r,Math.sin(a)*r,.4+Math.random()*1.5)}
// Original human-like explorer avatar visible in reflections/encounters; gameplay camera is first person.
function human(color=0x314c67){const g=new THREE.Group();const skin=mat(0xc58f70),cloth=mat(color);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.38,.9,6,10),cloth);body.position.y=1.25;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.32,16,12),skin);head.position.y=2.15;head.castShadow=true;g.add(head);for(const x of [-.48,.48]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.11,.7,5,8),cloth);arm.position.set(x,1.35,0);arm.rotation.z=x<0?.12:-.12;g.add(arm);const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.14,.75,5,8),mat(0x202b31));leg.position.set(x*.55,.45,0);g.add(leg)}return g}
const playerEcho=human(0x3e6076);playerEcho.position.set(0,0,-3);playerEcho.rotation.y=Math.PI;scene.add(playerEcho);
// Wildlife creatures: original silhouettes, not Pokémon assets.
const creatures=[];function creature(x,z){const g=new THREE.Group();const c=mat(0x6e765f),dark=mat(0x343c31);const body=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),c);body.scale.set(1.25,.8,.9);body.position.y=1;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.62,14,10),c);head.position.set(0,1.35,.95);g.add(head);for(const x2 of [-.55,.55]){for(const z2 of [-.5,.5]){const l=new THREE.Mesh(new THREE.CapsuleGeometry(.1,.65,4,6),dark);l.position.set(x2,0.55,z2);g.add(l)}}g.position.set(x,0,z);g.userData={hp:100,name:['Cervo de Bruma','Lince Solar','Raposa de Cinza'][Math.floor(Math.random()*3)],alive:true,phase:Math.random()*6};scene.add(g);creatures.push(g)}
creature(5,-10);creature(-13,-8);creature(18,12);
const particles=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xdde8d2,size:.08,transparent:true,opacity:.6}));const pa=[];for(let i=0;i<800;i++){pa.push((Math.random()-.5)*180,Math.random()*22,(Math.random()-.5)*180)}particles.geometry.setAttribute('position',new THREE.Float32BufferAttribute(pa,3));scene.add(particles);
let xp=0,level=1,energy=100,target=null,combat=false,missionDone=false;const $=id=>document.getElementById(id);function updateHud(){$('xp').textContent=xp;$('level').textContent=level;$('energy').textContent=Math.round(energy)}
function nearest(){let best=null,d=9;for(const c of creatures)if(c.userData.alive){const dd=c.position.distanceTo(camera.position);if(dd<d){d=dd;best=c}}return best}
function interact(){const c=nearest();if(c){target=c; $('dialogText').textContent=`Você encontrou ${c.userData.name}. O comportamento é territorial, mas parece receptivo à energia do seu equipamento.`;$('dialog').classList.remove('hidden');$('dialogBtn').onclick=()=>{$('dialog').classList.add('hidden');startCombat()};}else{$('mission').textContent='Nada próximo. Siga pelo vale e observe os sinais de vida.'}}
function startCombat(){const c=nearest();if(!c)return;target=c;combat=true;$('combat').classList.remove('hidden');$('enemyName').textContent=c.userData.name;updateCombat()}
function updateCombat(){$('enemyHp').style.width=Math.max(0,target?.userData.hp||0)+'%'}
function action(a){if(!combat||!target)return;if(a==='guard'){energy=Math.min(100,energy+8);$('mission').textContent='Defesa estabilizada. Escolha sua próxima ação.'}else if(a==='pulse'){const dmg=18+Math.random()*16;target.userData.hp-=dmg;energy=Math.max(0,energy-8);if(target.userData.hp<=0){target.userData.alive=false;target.visible=false;combat=false;xp+=50;if(xp>=100){xp-=100;level++}$('combat').classList.add('hidden');$('mission').textContent='Ameaça neutralizada. Procure outro sinal de vida.'}}else{if(target.userData.hp<45){target.userData.alive=false;target.visible=false;combat=false;xp+=80;energy=Math.max(0,energy-15);$('combat').classList.add('hidden');$('mission').textContent='Vínculo estabelecido. A expedição continua.'}else $('mission').textContent='A criatura ainda está instável. Reduza sua energia primeiro.'}updateCombat();updateHud()}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);const speed=(keys.ShiftLeft||keys.ShiftRight?8:4)*dt;const dir=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(dir.lengthSq())dir.normalize();controls.moveRight(dir.x*speed);controls.moveForward(dir.z*speed);if(keys.Space&&camera.position.y<=2.01)camera.position.y=5;else camera.position.y+=(2-camera.position.y)*Math.min(1,dt*8);camera.position.y=Math.max(2,camera.position.y);for(const c of creatures)if(c.userData.alive){c.rotation.y+=Math.sin(clock.elapsedTime+c.userData.phase)*dt*.15;c.position.x+=Math.sin(clock.elapsedTime*.5+c.userData.phase)*dt*.12;c.position.z+=Math.cos(clock.elapsedTime*.4+c.userData.phase)*dt*.12}particles.rotation.y+=dt*.01;renderer.render(scene,camera)}animate();setTimeout(()=>$('loading').remove(),700);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});updateHud();
